version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: Any CPU
configuration: Release

build:
  parallel: true
  project: ZConfig.sln
  publish_wap: false
  publish_wap_xcopy: false
  publish_azure: false
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

  verbosity: minimal

artifacts:
  - path: ZConfigParser\**\*.nupkg



deploy:
  provider: NuGet
  api_key:
    secure: ZMlpQhGj5wLYQ+kCa34FwWukeodzUWSvA8kV9QKyUgQf0CqJnOWSaZeVmFEsYM2e
  skip_symbols: false
  artifact: /.*\.nupkg/